apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitwardenrs.fullname" . }}
  labels:
  {{- include "bitwardenrs.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.bitwardenrs.websockets.enabled }}
    - port: {{ .Values.bitwardenrs.websockets.port }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  {{- end }}
  {{- with .Values.service.additionalSpec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  selector:
  {{- include "bitwardenrs.selectorLabels" . | nindent 4 }}
