{{- if (include "deconz.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "deconz.fullname" . }}
  labels:
    {{- include "deconz.labels" . | nindent 4 }}
type: Opaque
data:
  vnc-password: {{ required "You must specify a VNC password when not supplying an existing secret" .Values.vnc.password | b64enc | quote }}
{{- end }}