{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "node-feature-discovery.fullname" . }}-master
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    # when using command line flag --resource-labels to create extended resources
    # you will need to uncomment "- nodes/status"
    # - nodes/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-feature-discovery.fullname" . }}-master
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "node-feature-discovery.fullname" . }}-master
subjects:
  - kind: ServiceAccount
    name: {{ include "node-feature-discovery.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}