apiVersion: v1
kind: Secret
metadata:
  name: {{ template "digitalocean-dyndns.fullname" . }}
  labels:
    app: {{ template "digitalocean-dyndns.name" . }}
    chart: {{ template "digitalocean-dyndns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  digitalocean-dyndns-apikey: {{ .Values.digitialocean.token | b64enc | quote }}